### ISSUE TITLE
Video Statistics wont turn off on N64 (Nintendo 64)

### ISSUE THREAD

**Issue by NickSchindler** [Takiiiiiiii/M17#13]
Anyone know how to get the video statistics to turn off on the N64 games.  When I launch a game, the video statistics show up on almost half the screen.  I've tried to go into every option available on the current retroarch on this build and there is no where to turn them off where they wont show on screen.

**Comment by jbrepogmailcom** [comment]
You closed the issue, but you did not explain how you turned the debug info off. I have same problem, how did you do it?
