### ISSUE TITLE
N64 games show "Video Statistics" on the left side of the screen.

### ISSUE THREAD

**Issue by evandrolellis** [Takiiiiiiii/M17#2]
Hello! 
N64 games show "Video Statistics" on the left side of the screen. This is default in this build of the M17 core. 
How do I disable this?

**Comment by williamtwomey** [comment]
```
fps_show = "false"
framecount_show = "false"
statistics_show = "false"
```

in minigui/gbx66.cfg

**Comment by Takiiiiiiii** [comment]
> ```
> fps_show = "false"
> framecount_show = "false"
> statistics_show = "false"
> ```
> 
> in minigui/gbx66.cfg

This is correct.
